sonar.projectKey=YOUR_ORGANIZATION_OR_USERNAME_django-project
sonar.organization=YOUR_ORGANIZATION_OR_USERNAME
sonar.projectName=Grace Django Project
sonar.projectVersion=1.0

# Define source code directory relative to git root
sonar.sources=myproject

# Language settings
sonar.python.version=3.10, 3.11, 3.12

# Exclusions for migrations, static files, and standard project artifacts
sonar.exclusions=**/migrations/**,**/mystatic/**,**/templates/**,**/.vscode/**
